# Generated by Django 4.0.5 on 2022-06-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('urllong', models.CharField(max_length=100)),
                ('urlshort', models.CharField(max_length=50)),
                ('QRphotoname', models.CharField(max_length=100)),
            ],
        ),
    ]
